Client/Models/ErrorViewModel.cs
namespace Client.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Client/Controllers/AuthController.cs
using API.DTOs.Auth;
using Client.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace Client.Controllers;

public class AuthController : Controller
{
    private readonly IAuthRepository repository;

    public AuthController(IAuthRepository repository)
    {
        this.repository = repository;
    }

    public IActionResult Index()
    {
        return View();
    }

    [HttpGet]
    public IActionResult Login()
    {

        if (User.Identity.IsAuthenticated)
        {
            return RedirectToRoute(new { controller = "Employee", action = "Index" });
        }
        return View();
    }


    [HttpPost]
    public async Task<IActionResult> Login(SigninDto signDto)
    {

        var result = await repository.SignIn(signDto);
        if (result.Code == 200)
        {
            var token = result?.Data?.Token;
            Console.WriteLine("token : " + token);
            TempData["Success"] = "Berhasil Login";
            //HttpContext.Session.SetString("JWToken", token);
            HttpContext.Session.SetString("JWToken", token);
            return RedirectToRoute(new { controller = "Employee", action = "Index" });
        }

        TempData["Error"] = result.Message;
        return RedirectToAction(nameof(Login));
    }

    public IActionResult Logout()
    {
        HttpContext.Session.Clear();
        return RedirectToAction(nameof(Login));
    }

    [HttpGet]
    public IActionResult SignUp()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> SignUp(RegisterDto registerDto)
    {
        var result = await repository.Register(registerDto);
        if (result.Code == 201)
        {
            TempData["Success"] = "Account anda berhasil dibuat";
            return RedirectToAction(nameof(Login));
        }

        TempData["Error"] = result.Message;
        return RedirectToAction(nameof(Login));
    }
}

Client/Controllers/EmployeeController.cs
using API.DTOs.Employees;
using API.Utilities.Enums;
using Client.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Client.Controllers;

[Authorize(Roles = $"{nameof(RoleLevel.User)}")]
public class EmployeeController : Controller
{
    private readonly IEmployeeRepository repository;

    public EmployeeController(IEmployeeRepository repository)
    {
        this.repository = repository;
    }

    public async Task<IActionResult> Index()
    {
        var result = await repository.Get();
        Console.WriteLine(result);
        var ListEmployee = new List<GetEmployeeDto>();

        if (result?.Data != null)
        {
            ListEmployee = result.Data.ToList();
        }
        else
        {
            TempData["Error"] = result.Message;
        }


        return View(ListEmployee);
    }

    public async Task<IActionResult> Details(Guid guid)
    {
        var result = await repository.Get(guid);
        var employee = new GetEmployeeDto();

        if (result.Data != null)
        {
            employee = result.Data;
        }
        return View(employee);
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(GetEmployeeDto newEmploye)
    {

        var result = await repository.Post(newEmploye);
        if (result.Code == 201)
        {
            TempData["Success"] = "Data berhasil masuk";
            return RedirectToAction(nameof(Index));
        }
        else if (result.Code == 409)
        {
            ModelState.AddModelError(string.Empty, result.Message);
            return View();
        }

        TempData["Error"] = result.Message;
        return RedirectToAction(nameof(Index));

    }

    [HttpGet]
    public async Task<IActionResult> Edit(Guid guid)
    {
        var result = await repository.Get(guid);
        var employee = new GetEmployeeDto();

        if (result.Data != null)
        {
            employee = result.Data;
        }
        return View(employee);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(GetEmployeeDto updateEmployee)
    {

        var result = await repository.Put(updateEmployee);
        if (result.Code == 200)
        {
            TempData["Success"] = result.Message;
            return RedirectToAction(nameof(Index));
        }

        TempData["Error"] = result.Message;
        return RedirectToAction(nameof(Index));
    }


    [HttpPost]
    public async Task<IActionResult> DeletePOST(Guid guid)
    {
        Console.WriteLine("guid : " + guid);
        var result = await repository.Delete(guid);
        if (result.Code == 200)
        {
            TempData["Success"] = "Data berhasil dihapus";
            return RedirectToAction(nameof(Index));
        }
        else if (result.Code == 404 || result.Code == 500)
        {
            TempData["Error"] = result.Message;
            return RedirectToAction(nameof(Index));
        }


        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> Charts()
    {
        ChartEmployeeDto chartData = new ChartEmployeeDto();
        var response = await repository.Get();
        var employees = response.Data;

        if (response.Code == 200)
        {
            chartData.GenderCount["Female"] = employees.Where(e => e.Gender == GenderEnum.Female).Count();
            chartData.GenderCount["Male"] = employees.Where(e => e.Gender == GenderEnum.Male).Count();

            var monthNames = new List<string>
            {
                "January", "February", "March", "April", "May", "June",
                "July", "August", "September", "October", "November", "December"
            };

            // Group birth dates by month name, set count to 0 for missing months, and order the results
            var birthMonthCounts = monthNames
                .GroupJoin(employees,
                    monthName => monthName,
                    employee => employee.BirthDate.ToString("MMMM"),
                    (monthName, groupEmployee) => new { Month = monthName, Count = groupEmployee.Count() })
                .OrderBy(entry => monthNames.IndexOf(entry.Month));

            foreach (var entry in birthMonthCounts)
            {
                chartData.BirthMonthCount.Add(entry.Month, entry.Count);
            }

            return View(chartData);
        }

        TempData["Error"] = response.Message;
        return View(null);
    }
}

Client/Controllers/HomeController.cs
using Client.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Client.Controllers;

//[Authorize]
public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {

        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [AllowAnonymous]
    [HttpGet("/Unauthorized")]
    public IActionResult Unauthorized()
    {
        return View("401");
    }

    [AllowAnonymous]
    [Route("/NotFound")]
    public IActionResult NotFound()
    {
        return View("404");
    }

    [AllowAnonymous]
    [Route("/Forbidden")]
    public IActionResult Forbidden()
    {
        return View("403");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Client/Controllers/LatihanController.cs
using Microsoft.AspNetCore.Mvc;

namespace Client.Controllers
{
    public class LatihanController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Testing()
        {
            return View();
        }


    }
}

Client/Controllers/PokemonController.cs
using Microsoft.AspNetCore.Mvc;

namespace Client.Controllers
{
    public class PokemonController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

    }
}

Client/Views/Employee/Charts.cshtml
@model API.DTOs.Employees.ChartEmployeeDto

@if (TempData["Success"] != null)
{
    <script>
        Swal.fire({
            title: '@(TempData["Success"])',
            icon: 'success',
            confirmButtonText: 'OK'
        });

    </script>
}
else if (TempData["Error"] != null)
{
    <script>
        Swal.fire({
            title: '@(TempData["Error"])',
            icon: 'error',
            confirmButtonText: 'OK'
        });

    </script>
}

<h1 class="mb-5">Dashboard</h1>

@if(Model != null){
    <h5>Gender Percentage</h5>
    <div id="donutChart" style="width: 600px; height: 600px;"></div>

    <h5>Employees' birth month</h5>
    <div id="barChart"></div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
      crossorigin="anonymous"
    ></script>

    <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
    <script>
        var donutOptions = {
            chart: {
                type: "donut",
            },
            series: [@(Model.GenderCount["Female"]), @(Model.GenderCount["Male"])],

            labels: ["Female", "Male"],
            plotOptions: {
                pie: {
                    donut: {
                        size: "20%",
                        labels: {
                            show: true,
                        },
                    },
                },
            },
        };

        var donutChart = new ApexCharts(document.querySelector("#donutChart"), donutOptions);

        donutChart.render();



        var barOptions = {
            series: [
                {
                    name: "employee count",
                    data: [@(Model.BirthMonthCount["January"]), @(Model.BirthMonthCount["February"]), @(Model.BirthMonthCount["March"]), @(Model.BirthMonthCount["April"]), @(Model.BirthMonthCount["May"]), @(Model.BirthMonthCount["June"]), @(Model.BirthMonthCount["July"]), @(Model.BirthMonthCount["August"]), @(Model.BirthMonthCount["September"]), @(Model.BirthMonthCount["October"]), @(Model.BirthMonthCount["November"]), @(Model.BirthMonthCount["December"])],
                },
            ],
            chart: {
                height: 350,
                type: "bar",
            },
            plotOptions: {
                bar: {
                    borderRadius: 10,
                    dataLabels: {
                        position: "top", // top, center, bottom
                    },
                },
            },
            dataLabels: {
                enabled: true,
                formatter: function (val) {
                    return val;
                },
                offsetY: 20,
                style: {
                    fontSize: "12px",
                    colors: ["#304758"],
                },
            },

            xaxis: {
                categories: [
                    "Jan",
                    "Feb",
                    "Mar",
                    "Apr",
                    "May",
                    "Jun",
                    "Jul",
                    "Aug",
                    "Sep",
                    "Oct",
                    "Nov",
                    "Dec",
                ],
                position: "top",
                axisBorder: {
                    show: false,
                },
                axisTicks: {
                    show: false,
                },
                crosshairs: {
                    fill: {
                        type: "gradient",
                        gradient: {
                            colorFrom: "#D8E3F0",
                            colorTo: "#BED1E6",
                            stops: [0, 100],
                            opacityFrom: 0.4,
                            opacityTo: 0.5,
                        },
                    },
                },
                tooltip: {
                    enabled: true,
                },
            },
            yaxis: {
                axisBorder: {
                    show: false,
                },
                axisTicks: {
                    show: false,
                },
                labels: {
                    show: false,
                    formatter: function (val) {
                        return val;
                    },
                },
            },
            title: {
                text: "count of employees' birth month",
                floating: true,
                offsetY: 330,
                align: "center",
                style: {
                    color: "#444",
                },
            },
        };

        let barChart = new ApexCharts(document.querySelector("#barChart"), barOptions);
        barChart.render();
    </script>
}

Client/Views/Employee/Create.cshtml
@model API.DTOs.Employees.GetEmployeeDto

@{
    ViewData["Title"] = "Create";
}

<h1>Create New Employee</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form action="/Employee/Create" method="POST">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group mb-3" hidden>
                <label asp-for="Guid" class="control-label"></label>
                <input asp-for="Guid" class="form-control" />
                <span asp-validation-for="Guid" class="text-danger"></span>
            </div>
            <div class="form-group mb-3" hidden>
                <label asp-for="Nik" class="control-label"></label>
                <input asp-for="Nik" class="form-control" />
                <span asp-validation-for="Nik" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="BirthDate" class="control-label"></label>
                <input asp-for="BirthDate" type="date" class="form-control" value="@(new DateTime(2000, 01, 01).ToString("yyyy-MM-dd"))" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <div>Gender</div>
                <div class="form-check">
                    <input asp-for="Gender"
                           class="form-check-input"
                           type="radio"
                           name="gender"
                           id="female"
                           value="0"
                           checked />
                    <label asp-for="Gender" for="female"> Female </label>
                </div>
                <div class="form-check">
                    <input asp-for="Gender"
                           class="form-check-input"
                           type="radio"
                           name="gender"
                           id="male"
                           value="1" />
                    <label asp-for="Gender" for="male"> Male </label>
                </div>
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="HiringDate" class="control-label"></label>
                <input asp-for="HiringDate" type="date" class="form-control" />
                <span asp-validation-for="HiringDate" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" type="number" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Client/Views/Employee/Details.cshtml
@model API.DTOs.Employees.GetEmployeeDto

@{
    ViewData["Title"] = "Detail Employee";
}


<div class="card my-3">
    <div class="card-header">
        Detail Employee
    </div>
    <div class="card-body">
        <p><strong>First Name</strong>   : @Model.FirstName</p>
        <p><strong>Last Name</strong>    : @Model.LastName</p>
        <p><strong>NIK</strong>          : @Model.Nik</p>
        <p><strong>Gender</strong>       : @(Model.Gender == 0 ? "Female" : "Male")</p>
        <p><strong>Birth Date</strong>   : @Model.BirthDate.ToString("dd-MM-yyyy")</p>
        <p><strong>First Name</strong>   : @Model.HiringDate.ToString("dd-MM-yyyy")</p>
        <p><strong>Phone Number</strong> : @Model.PhoneNumber</p>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Client/Views/Employee/Edit.cshtml
@model API.DTOs.Employees.GetEmployeeDto
@using API.Utilities.Enums

@{
    ViewData["Title"] = "Edit Employee";
    Console.WriteLine(Model.BirthDate.ToString("yyyy-MM-dd"));
}

<h1>Edit Employee</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form action="/Employee/Edit" method="POST">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group mb-3" hidden>
                <label asp-for="Guid" class="control-label"></label>
                <input asp-for="Guid" class="form-control" value="@(Model.Guid)" />
                <span asp-validation-for="Guid" class="text-danger"></span>
            </div>
            <div class="form-group mb-3" hidden>
                <label asp-for="Nik" class="control-label"></label>
                <input asp-for="Nik" class="form-control" value="@(Model.Nik)" />
                <span asp-validation-for="Nik" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" value="@(Model.FirstName)" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" value="@(Model.LastName)" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="BirthDate" class="control-label"></label>
                <input asp-for="BirthDate" type="date" class="form-control" value="@(Model.BirthDate.ToString("yyyy-MM-dd"))" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <div>Gender</div>
                <div class="form-check">
                    <input asp-for="Gender"
                           class="form-check-input"
                           type="radio"
                           name="gender"
                           id="female"
                           value="0"
                           checked=@(Model.Gender == GenderEnum.Female ? true : false ) />
                    <label asp-for="Gender" for="female"> Female </label>
                </div>
                <div class="form-check">
                    <input asp-for="Gender"
                           class="form-check-input"
                           type="radio"
                           name="gender"
                           id="male"
                           value="1"
                           checked=@(Model.Gender == GenderEnum.Male ? true : false ) />
                    <label asp-for="Gender" for="male"> Male </label>
                </div>
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="HiringDate" class="control-label"></label>
                <input asp-for="HiringDate" type="date" class="form-control" value="@(Model.HiringDate.ToString("yyyy-MM-dd"))" />
                <span asp-validation-for="HiringDate" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" value="@(Model.Email)" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" value="@(Model.PhoneNumber)" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                
                <button type="submit" class="btn btn-primary">Update</button>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Client/Views/Home/401.cshtml
@{
    Layout = null;
}

<h1>401 Unauthorize</h1>

Client/Views/Home/403.cshtml
@{
    Layout = null;
}

<h1>403 Forbidden</h1>

Client/Views/Home/404.cshtml
@{
    Layout = null;
}

<h1>404 Not Found</h1>

Client/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Client/Views/Latihan/Testing.cshtml
@{
    Layout = "_LayoutTesting";
}
<h1>Hello World wkwk</h1>

Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Client</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Client.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.5/css/jquery.dataTables.css" />
    <link href="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.12/dist/sweetalert2.min.css" rel="stylesheet">
    

    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.4/moment.min.js"  crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.5/js/jquery.dataTables.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.12/dist/sweetalert2.all.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Client</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                        }
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Auth" asp-action="SignUp">SignUp</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Employee" asp-action="Charts">Charts</a>
                        </li>

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Auth" asp-action="Logout">Logout</a>
                            </li>
                        }
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Client - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    
    
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <link href="https://cdn.datatables.net/buttons/1.5.1/css/buttons.dataTables.min.css" rel="stylesheet" />

    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
    <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
    <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.0/js/buttons.colVis.min.js"></script>


    
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Client/Views/Shared/_LayoutTesting.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Client</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Client.styles.css" asp-append-version="true" />
</head>
<body>
    <h1>wkwkwk</h1>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Client</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Latihan" asp-action="Index">Latihan</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>